version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: estagioja
      POSTGRES_USER: estagioja
      POSTGRES_PASSWORD: estagioja
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 5432 -U estagioja -d estagioja"]
      interval: 10s
      timeout: 5s
      retries: 3

  api:
    build:
      context: ./EstagioJaAPI
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy

  app:
    build:
      context: ./estagioja_angular_webapp
      dockerfile: Dockerfile
    ports:
      - "4200:8080"
    depends_on:
      api:
        condition: service_started
